export default [
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "4",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "building 7 second floor",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "4",
    "category": "women's",
    "cleanliness": "",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "stud basement ",
    "privacy": "2"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "the accessible washroom in macgregor",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "3",
    "gender": "4",
    "mirror": "5",
    "name": "hayden",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "4",
    "mirror": "4",
    "name": "Kitchen side bathroom on Black Hole, Random Hall",
    "privacy": "1"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "Macgregor, McCormick",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "2",
    "gender": "5",
    "mirror": "5",
    "name": "Single stalls on the 1st floor of building 14",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "men's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "Kresge",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "4",
    "category": "men's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "2",
    "name": "MIT Nano",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "4",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "4",
    "mirror": "3",
    "name": "building 1 floor 2",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "men's",
    "cleanliness": "4",
    "comments": "3",
    "gender": "4",
    "mirror": "4",
    "name": "3rd floor nano",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "4",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "4",
    "name": "koch institute.",
    "privacy": "4"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "men's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "3",
    "mirror": "5",
    "name": "E25 1st Floor",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "3",
    "category": "men's",
    "cleanliness": "3",
    "comments": "4",
    "gender": "3",
    "mirror": "5",
    "name": "dorm wing bathroom",
    "privacy": "2"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "3",
    "gender": "5",
    "mirror": "4",
    "name": "hayden <33",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "3",
    "category": "men's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "3",
    "name": "4th floor mit nano",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "2",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "3",
    "gender": "2",
    "mirror": "5",
    "name": "3rd floor of the gym",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "private bathroom in 66",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "women's",
    "cleanliness": "3",
    "comments": "3",
    "gender": "4",
    "mirror": "1",
    "name": "stata",
    "privacy": "3"
},
{
    "ambiance": "always at least one other person in there",
    "amenity": "5",
    "availability": "4",
    "category": "women's",
    "cleanliness": "2",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "e14 third floor atrium bathroom",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "3",
    "gender": "4",
    "mirror": "2",
    "name": "EC",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "4",
    "category": "women's",
    "cleanliness": "4",
    "comments": "3",
    "gender": "3",
    "mirror": "4",
    "name": "next or new vassar",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "building 66 basement single bathroom",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "5",
    "category": "women's",
    "cleanliness": "2",
    "comments": "4",
    "gender": "4",
    "mirror": "4",
    "name": "Cheney room",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "3",
    "name": "Mit nano",
    "privacy": "3"
},
{
    "ambiance": "",
    "amenity": "",
    "availability": "",
    "category": "",
    "cleanliness": "",
    "comments": "",
    "gender": "",
    "mirror": "",
    "name": "one of the basement ones",
    "privacy": ""
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "5",
    "category": "men's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "4",
    "mirror": "3",
    "name": "Stud 3",
    "privacy": "2"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "5",
    "category": "",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "4",
    "name": "There are 2. One in building 18. The other is a secret. Why would I tell?",
    "privacy": "4"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "MacGregor Lobby bathroom",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "1",
    "gender": "5",
    "mirror": "1",
    "name": "On the grass in front of the dome",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "4",
    "category": "women's",
    "cleanliness": "3",
    "comments": "3",
    "gender": "4",
    "mirror": "3",
    "name": "3rd floor of building 33, close to the course 11 bathrooms",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "2",
    "gender": "5",
    "mirror": "1",
    "name": "bathroom in my dorm",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "3",
    "name": "3rd floor of hayden",
    "privacy": "2"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "2",
    "comments": "3",
    "gender": "2",
    "mirror": "4",
    "name": "gender neutral bathroom outside the banana lounge",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "Next",
    "privacy": "2"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "3",
    "gender": "4",
    "mirror": "5",
    "name": "bathrooms by banana lounge",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "3",
    "gender": "4",
    "mirror": "1",
    "name": "Random buddy toilets",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "5",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "building 35, 2nd floor",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "4",
    "category": "men's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "Bathrooms in building 16 (across from stata)",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "the hayden stacks gender neutral single stall restrooms",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "3",
    "gender": "5",
    "mirror": "5",
    "name": "Builidng 66 basement ",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "2",
    "category": "",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "3",
    "name": "3rd floor of media center!",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "not telling bc i don't want people to go there but i will fill out the rest of the survey for the info",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "3",
    "gender": "5",
    "mirror": "3",
    "name": "hayden",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "1",
    "name": "random hall",
    "privacy": "3"
},
{
    "ambiance": "there's a line",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "3",
    "gender": "3",
    "mirror": "5",
    "name": "bathroom outside banana lounge",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "3",
    "gender": "3",
    "mirror": "4",
    "name": "tetazoo deep goodale bathroom",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "2",
    "availability": "4",
    "category": "women's",
    "cleanliness": "4",
    "comments": "4",
    "gender": "5",
    "mirror": "",
    "name": "mcc 7E campus side bathroom, stall closest to showers; the bathrooms in building 26(?) near the bridge-walk that heads toward stata",
    "privacy": "4"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "4",
    "gender": "4",
    "mirror": "2",
    "name": "In my dorm. Beast's Walcott bathroom ",
    "privacy": "4"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "2",
    "gender": "3",
    "mirror": "5",
    "name": "next house",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "women's",
    "cleanliness": "3",
    "comments": "3",
    "gender": "5",
    "mirror": "4",
    "name": "the bathroom near 1-190",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "3",
    "category": "men's",
    "cleanliness": "4",
    "comments": "3",
    "gender": "4",
    "mirror": "3",
    "name": "4th stall from the left in the bathroom on the 6th floor of 34 (or 36 or 38?) by the elevators",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "3",
    "gender": "4",
    "mirror": "4",
    "name": "Hayden 1st floor",
    "privacy": "4"
},
{
    "ambiance": "",
    "amenity": "",
    "availability": "",
    "category": "",
    "cleanliness": "",
    "comments": "",
    "gender": "",
    "mirror": "",
    "name": "i'm not giving away my secret locations ",
    "privacy": ""
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "4",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "2",
    "name": "whitehead",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "the all-gender bathrooms in the hallway next to Hayden courtyard",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "",
    "availability": "",
    "category": "women's",
    "cleanliness": "",
    "comments": "5",
    "gender": "5",
    "mirror": "",
    "name": "building 66",
    "privacy": ""
},
{
    "ambiance": "sometimes a person there",
    "amenity": "2",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "2",
    "mirror": "1",
    "name": "5e bemis second stall",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "4",
    "mirror": "2",
    "name": "Women\u2019s bathroom first floor building 16",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "5",
    "availability": "2",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "the bathroom in my suite",
    "privacy": "2"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "5",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "Hayden",
    "privacy": "5"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "3",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "dorm",
    "privacy": "2"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "4",
    "mirror": "5",
    "name": "bathroom outside my room",
    "privacy": "2"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "3",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "4",
    "name": "3rd floor of the infinite, bathroom by the center for theoretical physics.",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "women's",
    "cleanliness": "5",
    "comments": "3",
    "gender": "5",
    "mirror": "3",
    "name": "havent been there in a while but kresge bathrooms were very nice :> i once walked >0.5 mi total to shit there instead of my dorm bathroom",
    "privacy": "4"
},
{
    "ambiance": "",
    "amenity": "",
    "availability": "",
    "category": "",
    "cleanliness": "",
    "comments": "",
    "gender": "",
    "mirror": "",
    "name": "Nano lounge",
    "privacy": ""
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "",
    "comments": "3",
    "gender": "",
    "mirror": "3",
    "name": "the new bathroom right next to the Music Library",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "green building",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "MIT MEDICAL BATHROOMS IN E25 they are sexy",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "3",
    "gender": "4",
    "mirror": "5",
    "name": "Bathroom right outside the Athena lounge on stud 5, like directly outside it.",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "4",
    "availability": "4",
    "category": "women's",
    "cleanliness": "5",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "media lab ",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "3",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "3",
    "gender": "3",
    "mirror": "5",
    "name": "outside of lewis music library",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "3",
    "availability": "3",
    "category": "men's",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "building 31",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "4",
    "gender": "4",
    "mirror": "5",
    "name": "New Vassar single bathrooms",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "5",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "building 12 basement bathroom... open it back up",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "4",
    "mirror": "2",
    "name": "Bemis 2 bathroom",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "4",
    "availability": "3",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "4",
    "gender": "5",
    "mirror": "5",
    "name": "the restrooms in the hallway of building 14",
    "privacy": "3"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "1",
    "availability": "4",
    "category": "gender neutral",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "3",
    "name": "Designated multi-stall no-gender stairwell located directly below 14N-333333333333333333",
    "privacy": "3"
},
{
    "ambiance": "sometimes a person there",
    "amenity": "2",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "5",
    "gender": "3",
    "mirror": "4",
    "name": "macgregor near lobby first floor",
    "privacy": "5"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "3",
    "category": "women's",
    "cleanliness": "5",
    "comments": "5",
    "gender": "5",
    "mirror": "4",
    "name": "Basement of Building 66",
    "privacy": "4"
},
{
    "ambiance": "when i go in there's always a stall available",
    "amenity": "5",
    "availability": "5",
    "category": "gender neutral",
    "cleanliness": "4",
    "comments": "5",
    "gender": "5",
    "mirror": "5",
    "name": "single occupancy all gender restroom on the 4th floor of the dusp building",
    "privacy": "5"
}
]